name: CI

on:
  push:
    branches: [main]
  pull_request:          # optional but recommended
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      REGION: ${{ secrets.REGION }}
      SERVICE: ${{ secrets.SERVICE }}
      REPO: ${{ secrets.REPO }}

    steps:
      # 1 — Check out repo
      - uses: actions/checkout@v4

      # 2 — Set up Python for unit tests
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3 — Install Python dependencies & pytest
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # 4 — Run unit tests (if you have none yet, it still passes)
      - name: Run unit tests
        run: pytest -q

      # 5 — Build Docker image (self-contained)
      - name: Build Docker image
        run: docker build -t bank-default-api:${{ github.sha }} .

      # 6 — Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 7 — Set up gcloud CLI
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      # 8 — Build and push container with Cloud Build
      - name: Build and push container
        run: |
          gcloud builds submit --tag $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/bank-default-api:$GITHUB_SHA --quiet || echo "Build triggered, skipping log streaming error"

      # 9 — Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE --image=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/bank-default-api:$GITHUB_SHA --region=$REGION --platform=managed --allow-unauthenticated
