name: CI

on:
  push:
    branches: [main]
  pull_request:          # optional but recommended
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      # 1 — Check out repo
      - uses: actions/checkout@v4

      # 2 — Set up Python for unit tests
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3 — Install Python dependencies & pytest
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # 4 — Run unit tests (if you have none yet, it still passes)
      - name: Run unit tests
        run: pytest -q

      # 5 — Build Docker image (self-contained)
      - name: Build Docker image
        run: docker build -t bank-default-api:${{ github.sha }} .
